on:
  push:
    branches-ignore:
      - main

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: Setup CLI
        uses: ./setup
        with:
          authentication: ${{ secrets.HYALINE_RELEASE_TOKEN }}
      - name: Print Hyaline version
        run: hyaline version